spring:
  # Config server
  config:
    import: configserver:${dev.config.server.url}
  # dev routes
  cloud:
    gateway:
      routes:
        ## DISCOVERY-SERVICE ROUTE
        - id: discovery-service
          uri: ${dev.eureka.url}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        ## DISCOVERY-SERVER STATIC RESOURCES ROUTE
        - id: discovery-service-static
          uri: ${dev.eureka.url}
          predicates:
            - Path=/eureka/**

        ## COUPON-SERVICE ROUTE
        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - AuthenticationFilter
