spring:
  application:
    name: api-gateway
  profiles:
    active: dev

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/api/v1/coupons/**

#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/health

server:
  port: 8765