server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: dev

  cloud:
    gateway:
      ## Api gateway config (routes)
      routes:
        # ==================================== COUPON SERVICE ====================================
        ## Coupon-service::Health check
        - id: coupon-service-health-check
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/actuator/health
            - Method=GET
          filters:
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}

        ## Coupon-service::GET-all-coupons
        - id: coupon-service-get-all-coupons
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Coupon-service::GET-coupon
        - id: coupon-service-get-coupon
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Coupon-service::POST-coupon
        - id: coupon-service-post-coupon
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        ## Coupon-service::PUT-coupon
        - id: coupon-service-put-coupon
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons/**
            - Method=PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        ## Coupon-service::DELETE-coupon
        - id: coupon-service-delete-coupon
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons/**
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE DELETE

        # ==================================== PRODUCT SERVICE ====================================
        ## Product-service::Health check
        - id: product-service-health-check
          uri: lb://product-service
          predicates:
            - Path=/product-service/actuator/health
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}

        ## Product-service::GET-all-products
        - id: product-service-get-all-products
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ ROLE_USER READ

        ## Product-service::GET-product
        - id: product-service-get-product
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ ROLE_USER READ

        ## Product-service::POST-product
        - id: product-service-post-product
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        ## Product-service::PUT-product
        - id: product-service-put-product
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products/**
            - Method=PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        ## Product-service::DELETE-product
        - id: product-service-delete-product
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products/**
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE DELETE

        # ==================================== ORDER SERVICE ====================================
        ## Order-service::Health check
        - id: order-service-health-check
          uri: lb://order-service
          predicates:
            - Path=/order-service/actuator/health
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}

        ## Order-service::GET-all-orders
        - id: order-service-get-all-orders
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Order-service::GET-order
        - id: order-service-get-order
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ ROLE_USER READ

        ## Order-service::POST-order
        - id: order-service-post-order
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE ROLE_USER READ WRITE

        ## Order-service::PATCH-order
        - id: order-service-patch-order
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders/**
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        ## Order-service::DELETE-order
        - id: order-service-delete-order
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders/**
            - Method=PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE DELETE

        # ==================================== INVENTORY SERVICE ====================================
        ## Inventory-service::Health check
        - id: inventory-service-health-check
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/actuator/health
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/inventory-service/(?<segment>.*), /${segment}

        ## Inventory-service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/api/v1/inventories/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/inventory-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE DELETE

        # ==================================== IDENTITY SERVICE  - AUTHENTICATION ====================================
        ## Identity-service::Authentication
        - id: identity-service-authentication
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/auth/token
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        # ==================================== IDENTITY SERVICE  - USERS ====================================
        ## Identity-service::GET-health-check
        - id: identity-service-health-check
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/actuator/health
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        ## Identity-service::GET-all-users
        - id: identity-service-get-all-users
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Identity-service::POST-user
        - id: identity-service-post-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        ## Identity-service::GET-user
        - id: identity-service-get-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Identity-service::DELETE-user
        - id: identity-service-delete-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users/**
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE DELETE

        # ==================================== IDENTITY SERVICE - ROLES ====================================
        ## Identity-service::GET-roles
        - id: identity-service-get-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ

        ## Identity-service::POST-role
        - id: identity-service-create-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN READ WRITE

        # ==================================== MAILING SERVICE ====================================
        ## Mailing-service::Health check
        - id: mailing-service-health-check
          uri: lb://mailing-service
          predicates:
            - Path=/mailing-service/actuator/health
            - Method=GET
          filters:
            - RewritePath=/mailing-service/(?<segment>.*), /${segment}