spring:
  # Config server
  config:
    import: configserver:${dev.config.server.url}
  # dev routes
  cloud:
    gateway:
      routes:
        ## DISCOVERY-SERVICE ROUTE
        - id: discovery-service
          uri: ${dev.eureka.url}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        ## DISCOVERY-SERVER STATIC RESOURCES ROUTE
        - id: discovery-service-static
          uri: ${dev.eureka.url}
          predicates:
            - Path=/eureka/**

# Discovery client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${dev.eureka.defaultZone}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true