server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
## Api gateway config (routes)
  cloud:
    gateway:
      routes:
        ## Coupon-service
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Product-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Inventory-service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/api/v1/inventories/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/inventory-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Identity-service::Authentication
        - id: identity-service-authentication
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/auth/token
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        ## Identity-service::Get-all-users
        - id: identity-service-get-all-users
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Identity-service::POST-user
        - id: identity-service-post-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        ## Identity-service::GET-user
        - id: identity-service-get-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Identity-service::GET-roles
        - id: identity-service-get-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        ## Identity-service::POST-role
        - id: identity-service-create-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter
