server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
## Api gateway config (routes)
  cloud:
    gateway:
      routes:
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/api/v1/coupons/**
            #- Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/v1/products/**
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/api/v1/orders/**
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/api/v1/inventories/**
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/inventory-service/(?<segment>.*), /${segment}

        - id: identity-service-authentication
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/auth/token
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        - id: identity-service-register-user
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        - id: identity-service-get-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}

        - id: identity-service-create-roles
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/api/v1/roles
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/identity-service/(?<segment>.*), /${segment}
