spring:
  # Config server
  config:
    import: configserver:${stg.config.server.url}

  redis:
    host: ${stg.redis.host}
    port: ${stg.redis.port}

  rabbitmq:
    host: rabbitmq
    template:
      default-receive-queue: ${broker.coupon.queue}
      exchange: ${broker.coupon.exchange}
      routing-key: ${broker.coupon.routing-key}
