server:
  port: 0

spring:
  application:
    name: mailing-service
  profiles:
    active: dev

  ## Mailing config
  mail:
    host: ${mailing.host}
    port: ${mailing.port}
    username: ${mailing.username}
    password: ${mailing.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

## RabbitMq config
rabbitmq:
  queue: ${broker.mailing.queue}
  exchange: ${broker.mailing.exchange}
  routing-key: ${broker.mailing.routing-key}
