spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: mad
    password: Mad123**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9092
