server:
  port: 0

spring:
  application:
    name: order-service
  profiles:
    active: dev

rabbitmq:
  # Mailing config
  mailing:
    queue: ${broker.mailing.queue}
    exchange: ${broker.mailing.exchange}
    routing-key: ${broker.mailing.routing-key}
  # History config
  history:
    queue: ${broker.history.queue}
    exchange: ${broker.history.exchange}
    routing-key: ${broker.history.routing-key}
