server:
  port: 0

spring:
  application:
    name: inventory-service
  profiles:
    active: dev

rabbitmq:
  product :
    queue: ${broker.product.queue}
    exchange: ${broker.product.exchange}
    routing-key: ${broker.product.routing-key}
  history:
    queue: ${broker.history.queue}
    exchange: ${broker.history.exchange}
    routing-key: ${broker.history.routing-key}
