server:
  port: 8888

spring:
  application:
    name: config-server
#  profiles:
#     stg
  cloud:
    config:
      server:
        git:
          uri: https://github.com/med-amine01/spring-config-server
          clone-on-start: true
