server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          clone-on-start: true
          username: med-amine01
          password: ${GIT_TOKEN}
